- import_playbook: ../dotnet/core.yaml    # PowerShell Core depends on having .NET available

- name: PowerShell Core
  hosts: 127.0.0.1
  connection: local

  tasks:
    - name: Install PowerShell Core
      command: dotnet tool install -g powershell
      args:
        creates: ~/.dotnet/tools/pwsh
