- import_playbook: ../dotnet/core.yaml    # PowerShell Core depends on having .NET Core available

- name: PowerShell Core
  hosts: 127.0.0.1
  connection: local

  vars:
    is_mac: "{{ ansible_distribution == 'MacOSX' }}"

  tasks:
    # Linux

    - name: Install PowerShell Core (Linux)
      command: dotnet tool install -g powershell
      args:
        creates: ~/.dotnet/tools/pwsh
      when: not is_mac

    # macOS

    - name: Install PowerShell Core (macOS)
      homebrew_cask:
        name: powershell
      when: is_mac
