- name: "Ruby"
  hosts: 127.0.0.1
  connection: local

  tasks:
    - name: "Install package"
      become: yes
      ansible.builtin.dnf:
        name: "{{ item }}"
      loop:
        - ruby-build-rbenv

    - name: "Enable rbenv in bash"
      ansible.builtin.blockinfile:
        path: ~/.bashrc
        marker: "### {mark} Ansible managed: Ruby"
        block: |
          eval "$(rbenv init - --no-rehash bash)"
