- name: Ruby (customization)
  hosts: 127.0.0.1
  connection: local

  vars:
    ruby_version_primary: 3.0.3
    ruby_versions:
    - 2.7.5
    - "{{ ruby_version_primary }}"

  tasks:
    # Need to update versions in case this is being re-run to get a newer Ruby
    - name: Update available Ruby versions
      shell: git -C ~/.rbenv/plugins/ruby-build pull
      ignore_errors: yes

    - name: Install Ruby
      shell: ~/.rbenv/bin/rbenv install {{ item }}
      args:
        creates: ~/.rbenv/versions/{{ item }}/bin/ruby
      loop: "{{ ruby_versions }}"

    - name: Use Ruby {{ ruby_version_primary }} by default
      shell: ~/.rbenv/bin/rbenv global {{ ruby_version_primary }}
