- name: "Ruby (customization)"
  hosts: 127.0.0.1
  connection: local

  vars:
    ruby_version_primary: 3.4.10
    ruby_versions:
    - 2.7.8  # For anything which is unhappy with 3.x
    - "{{ ruby_version_primary }}"

  tasks:
    - name: "Install Ruby"
      ansible.builtin.shell: rbenv install {{ item }}
      args:
        creates: ~/.rbenv/versions/{{ item }}/bin/ruby
      loop: "{{ ruby_versions }}"

    - name: "Use Ruby {{ ruby_version_primary }} by default"
      ansible.builtin.shell: rbenv global {{ ruby_version_primary }}
