- name: Ruby (customization)
  hosts: 127.0.0.1
  connection: local

  vars:
    ruby_version: 2.7.2

  tasks:
    # Need to update versions in case this is being re-run to get a newer Ruby
    - name: Update available Ruby versions
      shell: git -C ~/.rbenv/plugins/ruby-build pull
      ignore_errors: yes

    - name: Install Ruby {{ ruby_version }}
      shell: ~/.rbenv/bin/rbenv install {{ ruby_version }}
      args:
        creates: ~/.rbenv/versions/{{ ruby_version }}/bin/ruby
      register: ruby_install

    - name: Use Ruby {{ ruby_version }} by default
      shell: ~/.rbenv/bin/rbenv global {{ ruby_version }}
      when: ruby_install.changed
