- name: Azure (az)
  hosts: 127.0.0.1
  connection: local

  vars:
    az_distribution_release: "{{ 'eoan' if ansible_distribution_release == 'focal' else ansible_distribution_release }}"
    is_mac: "{{ ansible_distribution == 'MacOSX' }}"

  tasks:
    # Linux

    - name: Add Microsoft APT package key
      become: yes
      apt_key:
        url: https://packages.microsoft.com/keys/microsoft.asc
      when: not is_mac

    - name: Add Azure CLI APT package repository
      become: yes
      apt_repository:
        repo: deb [arch=amd64] https://packages.microsoft.com/repos/azure-cli {{ az_distribution_release }} main
        filename: azure-cli
        update_cache: no
      register: apt_repository
      when: not is_mac

    - name: Update APT package list
      become: yes
      apt:
        update_cache: yes
      when: apt_repository.changed
      register: apt_update
      retries: 5
      until: apt_update is success

    - name: Install Azure CLI (Linux)
      become: yes
      apt:
        package: azure-cli
      when: not is_mac

    # macOS

    - name: Install Azure CLI (macOS)
      homebrew:
        name: azure-cli
      when: is_mac
