- name: Azure (VS Code)
  hosts: 127.0.0.1
  connection: local

  tasks:
    - name: Install VS Code Extensions
      command: code --install-extension {{ item }}
      args:
        creates: ~/.vscode/extensions/{{ item }}-*/package.json
      loop:
        - ms-azure-devops.azure-pipelines
        - msazurermtools.azurerm-vscode-tools
