- name: Go
  hosts: 127.0.0.1
  connection: local

  vars:
    go_version: 1.25.1

  tasks:
    - name: Create binary folder
      become: yes
      file:
        path: /opt/google/go{{ go_version }}
        state: directory

    - name: Install Go
      become: yes
      unarchive:
        src: https://dl.google.com/go/go{{ go_version }}.linux-amd64.tar.gz
        dest: /opt/google/go{{ go_version }}
        remote_src: yes
        creates: /opt/google/go{{ go_version }}/go/bin/go
      register: go_download

    - name: Create symlink to /usr/local/go
      become: yes
      file:
        path: /usr/local/go
        src: /opt/google/go{{ go_version }}/go
        state: link

    - name: Add Go to the PATH
      lineinfile:
        path: ~/.bashrc
        line: export PATH=$PATH:/usr/local/go/bin

    - name: Create package/source folder
      file:
        path: ~/dev/go
        state: directory

    - name: Clean $GOPATH/pkg
      become: yes
      file:
        path: ~/dev/go/pkg
        state: absent
      when: go_download.changed

    - name: Set up environment (Common)
      blockinfile:
        path: ~/.bashrc
        marker: "### {mark} Ansible managed: Go support"
        block: |
          export PATH=$PATH:$HOME/dev/go/bin
          export GOPATH=$HOME/dev/go
