- name: Go
  hosts: 127.0.0.1
  connection: local

  vars:
    go_version: 1.15.5
    is_mac: "{{ ansible_distribution == 'MacOSX' }}"

  tasks:
    # Linux

    - name: Create binary folder
      become: yes
      file:
        path: /opt/google/go{{ go_version }}
        state: directory
      when: not is_mac

    - name: Install Go (Linux)
      become: yes
      unarchive:
        src: https://dl.google.com/go/go{{ go_version }}.linux-amd64.tar.gz
        dest: /opt/google/go{{ go_version }}
        remote_src: yes
        creates: /opt/google/go{{ go_version }}/go/bin/go
      register: go_download_linux
      when: not is_mac

    - name: Create symlink to /usr/local/go
      become: yes
      file:
        path: /usr/local/go
        src: /opt/google/go{{ go_version }}/go
        state: link
      when: not is_mac

    - name: Add Go to the PATH
      lineinfile:
        path: ~/.bashrc
        line: export PATH=$PATH:/usr/local/go/bin
      when: not is_mac

    # macOS

    - name: Install Go (macOS)
      homebrew:
        name: go
      register: go_download_mac
      when: is_mac

    # Common

    - name: Create package/source folder
      file:
        path: ~/dev/go
        state: directory

    - name: Clean $GOPATH/pkg
      become: yes
      file:
        path: ~/dev/go/pkg
        state: absent
      when: go_download_linux.changed or go_download_mac.changed

    - name: Set up environment (Common)
      blockinfile:
        path: ~/.bashrc
        marker: "### {mark} Ansible managed: Go support"
        block: |
          export PATH=$PATH:$HOME/dev/go/bin
          export GOPATH=$HOME/dev/go

          function switchgo() {
            version=$1
            if [ -z $version ]; then
              echo "Usage: switchgo [version]"
              return
            fi
            if ! command -v "go$version" > /dev/null 2>&1; then
              echo "version does not exist, downloading with commands: "
              echo "  go get golang.org/dl/go${version}"
              echo "  go${version} download"
              echo ""
              go get "golang.org/dl/go${version}"
              go${version} download
            fi
            go_bin_path=$(command -v "go$version")
            ln -sf "$go_bin_path" "$HOME/bin/go"
            echo "Switched to ${go_bin_path}"
          }
