- name: Saml2Aws
  hosts: 127.0.0.1
  connection: local

  vars:
    - version: "2.36.0"

  tasks:
    - name: Remove "dbus-x11" package which conflict with saml2aws
      apt:
        name: dbus-x11
        state: absent

    # see https://github.com/Versent/saml2aws#option-2-configure-pass-to-be-the-default-keyring
    - name: Enable pass backend and gnupg which encrypts passwords
      become: yes
      apt:
        name: "{{ packages }}"
      vars:
        packages:
          - pass
          - gnupg

    - name: Download and extract saml2aws
      unarchive:
        src: https://github.com/Versent/saml2aws/releases/download/v{{ version }}/saml2aws_{{ version }}_linux_amd64.tar.gz 
        dest: ~/bin
        remote_src: yes

    - name: Add saml2aws config file
      copy:
        src: saml2aws.config
        dest: ~/.saml2aws

    - name: Set up environment for saml2aws
      blockinfile:
        path: ~/.bashrc
        marker: "### {mark} Ansible managed: saml2aws support"
        block: |
          export AWS_PROFILE=em-nonprod-admin
          export SAML2AWS_KEYRING_BACKEND=pass
          export GPG_TTY="$( tty )"
          eval "$(saml2aws --completion-script-bash)"

