- name: Terragrunt Config
  hosts: 127.0.0.1
  connection: local

  tasks:
    - name: Create temp folder if not exist
      ansible.builtin.file:
        path: /tmp/terragrunt-cache
        state: directory
        mode: '0755'

    - name: Set up terragrunt envars
      blockinfile:
        path: ~/.bashrc
        marker: "### {mark} Ansible managed: terragrunt config"
        block: |
          # export TERRAGRUNT_DOWNLOAD="/tmp/terragrunt-cache"
          # export TERRAGRUNT_INCLUDE_EXTERNAL_DEPENDENCIES="true"
