- import_playbook: ../rust-lang/core.yaml    # diffr is installed with Rust's cargo package manager

- name: git (customization)
  hosts: 127.0.0.1
  connection: local

  vars:
    lazygit_version: 0.40.2

  tasks:
    - name: Create lazygit binary folder
      become: yes
      file:
        path: /opt/lazygit/{{ lazygit_version }}
        state: directory

    - name: Install lazygit
      become: yes
      unarchive:
        src: https://github.com/jesseduffield/lazygit/releases/download/v{{ lazygit_version }}/lazygit_{{ lazygit_version }}_Linux_x86_64.tar.gz
        dest: /opt/lazygit/{{ lazygit_version }}
        remote_src: yes
        creates: /opt/lazygit/{{ lazygit_version }}/lazygit
      register: lazygit_download

    - name: Create symlink to /usr/local/bin/lazygit
      become: yes
      file:
        path: /usr/local/bin/lazygit
        src: /opt/lazygit/{{ lazygit_version }}/lazygit
        state: link

    - name: Install diffr
      command: ~/.cargo/bin/cargo install diffr
      args:
        creates: ~/.cargo/bin/diffr

    - name: Install difftastic
      command: ~/.cargo/bin/cargo install difftastic
      args:
        creates: ~/.cargo/bin/difft

    - name: Download git-completion.bash
      get_url:
        url:  https://raw.githubusercontent.com/git/git/master/contrib/completion/git-completion.bash
        dest: ~/.git-completion.bash

    - name: Add bash completion for git
      blockinfile:
        path: ~/.bashrc
        marker: "### {mark} Ansible managed: git-completion.bash"
        block: |
          if [ -f ~/.git-completion.bash ]; then
            . ~/.git-completion.bash
          fi

    - name: Ensure ~/.config exists
      file:
        path: ~/.config
        state: directory
        mode: 0700

    - name: Create ~/.config/ripgrep
      copy:
        dest: ~/.config/ripgrep
        mode: 0755
        content: |
          --hidden

    - name: Set ripgrep configuration path
      lineinfile:
        path: ~/.bashrc
        line: export RIPGREP_CONFIG_PATH=$HOME/.config/ripgrep
