#########################################################################################
#
#  Note that import order here is important, so rearranging import lists
#  is *not* recommended.
#
#########################################################################################

- name: Configure machine for development work
  hosts: 127.0.0.1
  connection: local

##### Operating system packages and configuration

- import_playbook: core.yaml

##### Developer tools

# 1password
- import_playbook: 1password/core.yaml

# Visual Studio Code
- import_playbook: vscode/core.yaml

# Azure
- import_playbook: azure/az.yaml
- import_playbook: azure/azshell.yaml
- import_playbook: azure/storage-explorer.yaml

# Broot
- import_playbook: broot/core.yaml

# Docker
- import_playbook: docker/core.yaml

# .NET Core
- import_playbook: dotnet/core.yaml

# Flameshot
- import_playbook: flameshot/core.yaml

# git
- import_playbook: git/core.yaml

# GitHub
- import_playbook: github/gh.yaml
- import_playbook: github/hub.yaml

# golang
- import_playbook: golang/core.yaml

# Kubernetes
- import_playbook: kubectl/core.yaml

# Virtualization (QEMU/KVM on Linux, VirtualBox on macOS)
- import_playbook: virtualization/core.yaml

# Mono (.NET Framework)
- import_playbook: mono/core.yaml

# NodeJS
- import_playbook: nodejs/core.yaml

# Nomad
- import_playbook: nomad/core.yaml

# Postman
- import_playbook: postman/core.yaml

# PowerShell Core
- import_playbook: powershell-core/core.yaml

# Python
- import_playbook: python/core.yaml

# Ruby
- import_playbook: ruby/core.yaml

##### Applications (free)

# Alacritty (high performance terminal application)
- import_playbook: alacritty/core.yaml

# Firefox
- import_playbook: firefox/core.yaml

# Prettier version of ping w/ graphs
- import_playbook: prettyping/core.yaml

# Slack desktop application
- import_playbook: slack/core.yaml

# VideoLan Client (primarily for codecs)
- import_playbook: vlc/core.yaml

# Zoom
- import_playbook: zoom/core.yaml

##### Applications (commercial license required)

# Spotify
- import_playbook: spotify/core.yaml
