#########################################################################################
#
#  Note that import order here is important, so rearranging import lists
#  is *not* recommended.
#
#########################################################################################

- name: "Configure machine for development work"
  hosts: 127.0.0.1
  connection: local

##### Operating system packages and configuration

- import_playbook: core.yaml

##### Developer tools

# Visual Studio Code
- import_playbook: vscode/core.yaml

# bat
- import_playbook: bat/core.yaml

# Broot
- import_playbook: broot/core.yaml

# Docker
- import_playbook: docker/core.yaml

# .NET
- import_playbook: dotnet/core.yaml

# git
- import_playbook: git/core.yaml

# golang
# - import_playbook: golang/core.yaml

# Meld (2- and 3-way diff/merge tool)
- import_playbook: meld/core.yaml

# NodeJS
# - import_playbook: nodejs/core.yaml

# PowerShell
- import_playbook: powershell/core.yaml

# Python
# - import_playbook: python/core.yaml

# Ruby
# - import_playbook: ruby/core.yaml

# rust-lang
# - import_playbook: rust-lang/core.yaml

# Virtualization (QEMU/KVM)
- import_playbook: virtualization/core.yaml

##### Applications

# Alacritty (high performance terminal application)
- import_playbook: alacritty/core.yaml

# OneDrive
- import_playbook: onedrive/core.yaml

# Prettier version of ping w/ graphs
- import_playbook: prettyping/core.yaml

# RDP/X/VNC/SSH client
- import_playbook: remmina/core.yaml

# Slack desktop application
- import_playbook: slack/core.yaml

# Vivaldi (browser)
- import_playbook: vivaldi/core.yaml

# VLC video player (primarily for codecs)
- import_playbook: vlc/core.yaml
