- name: "Core OS packages"
  hosts: 127.0.0.1
  connection: local

  tasks:
    - ansible.builtin.set_fact: is_wsl={{ lookup('file', '/proc/version') is regex('(M|m)icrosoft') }}

    - name: "Create ~/bin"
      ansible.builtin.file:
        path: ~/bin
        state: directory
        mode: 0700

    - name: "Add ~/bin to PATH"
      ansible.builtin.lineinfile:
        path: ~/.bashrc
        line: export PATH=$PATH:~/bin

    - name: "Upgrade packages"
      become: yes
      ansible.builtin.dnf:
        name: "*"
        state: latest
        update_cache: yes

    - name: "Install core package"
      become: yes
      ansible.builtin.dnf:
        name: "{{ item }}"
      loop:
        - 7zip-standalone
        - dosfstools
        - exfatprogs
        - htop
        - jq
        - ncurses
        - ntfs-3g-system-compression
        - ntfsprogs
        - uuid
        - xclip

    - name: "[WSL] Enable WSL interop"
      become: yes
      ansible.builtin.copy:
        dest: /usr/lib/binfmt.d/WSLInterop.conf
        mode: 0644
        content: |
          :WSLInterop:M::MZ::/init:PF
      register: wsl_interop
      when: is_wsl

    - name: "[WSL] Restart systemd-binfmt"
      become: yes
      ansible.builtin.shell: systemctl restart systemd-binfmt
      when: is_wsl and wsl_interop.changed

    - name: "Ensure ~/.hushlogin exists"
      ansible.builtin.file:
        path: ~/.hushlogin
        state: touch
