- name: Core OS packages
  hosts: 127.0.0.1
  connection: local

  vars:
    distribution_fallback:
      'Pop!_OS': 'Ubuntu'
    distribution: "{{ distribution_fallback[ansible_distribution] | default(ansible_distribution) }}"
    is_ubu_22_04_or_newer: "{{ distribution == 'Ubuntu' and (ansible_distribution_major_version | int) >= 22 }}"

  tasks:
    - set_fact: is_wsl={{ lookup('file', '/proc/version') is regex('(M|m)icrosoft') }}

    - name: Disable auto-upgrade timer
      become: yes
      command:
        cmd: systemctl disable {{ item }}.timer
        removes: /etc/systemd/system/timers.target.wants/{{ item }}.timer
      loop:
        - apt-daily
        - apt-daily-upgrade

    - name: Create ~/bin
      file:
        path: ~/bin
        state: directory
        mode: 0700

    - name: Add ~/bin to PATH
      lineinfile:
        path: ~/.bashrc
        line: export PATH=$PATH:~/bin

    - name: Enable HTTPS APT support
      become: yes
      apt:
        name: "{{ packages }}"
      vars:
        packages:
          - apt-transport-https
          - ca-certificates
          - gnupg-agent
          - software-properties-common

    - name: Update APT package list
      become: yes
      apt:
        update_cache: yes
      register: apt_update
      retries: 5
      until: apt_update is success

    - name: Upgrade to latest APT packages
      become: yes
      apt:
        upgrade: "yes"

    - name: Install core packages
      become: yes
      apt:
        package: "{{ item }}"
      loop:
        - curl
        - dconf-editor
        - exfat-fuse
        - htop
        - inetutils-traceroute
        - jq
        - net-tools
        - p7zip-full
        - unzip
        - uuid
        - xclip

    - name: "[Ubuntu pre-22.04] Install exfat-utils"
      become: yes
      apt:
        package: exfat-utils
      when: not is_ubu_22_04_or_newer

    - name: "[Ubuntu 22.04+] Install exfatprogs"
      become: yes
      apt:
        package: exfatprogs
      when: is_ubu_22_04_or_newer

    - name: "[Non-WSL Ubuntu 22.04+] Install Gnome Extension Manager"
      become: yes
      apt:
        package: gnome-shell-extension-manager
      when: not is_wsl and is_ubu_22_04_or_newer

    - name: "[Non-WSL] Install snapd"
      become: yes
      apt:
        package: snapd
      when: not is_wsl

    - name: "[Non-WSL] Install snap core"
      become: yes
      command: snap install core
      args:
        creates: /snap/core/current/bin/bash
      when: not is_wsl

    - name: "[Non-WSL] Add /snap/bin to PATH"
      lineinfile:
        path: ~/.bashrc
        line: export PATH=$PATH:/snap/bin
      when: not is_wsl

    - name: Get installed package list
      package_facts: {}

    - name: Add dm-crypt to /etc/initramfs-tools/modules
      become: yes
      lineinfile:
        path: /etc/initramfs-tools/modules
        line: dm-crypt
      when: ansible_facts.packages["cryptsetup-initramfs"] is defined

    - name: "[WSL] Enable systemd"
      become: yes
      blockinfile:
        path: /etc/wsl.conf
        create: yes
        marker: "### {mark} Ansible managed: Enable systemd"
        block: |
          [boot]
          systemd=true
      when: is_wsl

    - name: Ensure ~/.hushlogin exists
      file:
        path: ~/.hushlogin
        state: touch
