- name: "Core OS customization (Gnome UI)"
  hosts: 127.0.0.1
  connection: local

  vars:
    kde_config:
      # Keyboard & mouse settings
      - file: kcminputrc
        group: Keyboard
        key: RepeatDelay
        value: "250"
      - file: kcminputrc
        group: Keyboard
        key: RepeatRate
        value: "25"
      - file: kwinrc
        group: Wayland
        key: VirtualKeyboardMode
        value: "0"
      # Keyboard shortcuts
      - file: kglobalshortcutsrc
        group: kwin
        key: "Window Maximize"
        value: "Meta+Up,Meta+PgUp,Maximize Window"
      - file: kglobalshortcutsrc
        group: kwin
        key: "Window Minimize"
        value: "Meta+Down,Meta+PgDown,Minimize Window"
      - file: kglobalshortcutsrc
        group: kwin
        key: "Window Quick Tile Bottom"
        value: "none,Meta+Down,Quick Time Window to the Bottom"
      - file: kglobalshortcutsrc
        group: kwin
        key: "Window Quick Tile Top"
        value: "none,Meta+Up,Quick Time Window to the Top"
      - file: kglobalshortcutsrc
        group: kwin
        key: "Show Desktop"
        value: "Meta+M,Meta+D,Show Desktop"

    fonts:
      # FiraCode Nerd Font
      - https://github.com/ryanoasis/nerd-fonts/raw/master/patched-fonts/FiraCode/FiraCodeNerdFontMono-Regular.ttf
      - https://github.com/ryanoasis/nerd-fonts/raw/master/patched-fonts/FiraCode/FiraCodeNerdFontMono-Bold.ttf
      # Iosevka
      - https://github.com/ryanoasis/nerd-fonts/raw/master/patched-fonts/Iosevka/IosevkaNerdFontMono-Regular.ttf
      - https://github.com/ryanoasis/nerd-fonts/raw/master/patched-fonts/Iosevka/IosevkaNerdFontMono-Italic.ttf
      - https://github.com/ryanoasis/nerd-fonts/raw/master/patched-fonts/Iosevka/IosevkaNerdFontMono-Bold.ttf
      - https://github.com/ryanoasis/nerd-fonts/raw/master/patched-fonts/Iosevka/IosevkaNerdFontMono-BoldItalic.ttf
      # JetBrainsMono Nerd Font
      - https://github.com/ryanoasis/nerd-fonts/raw/master/patched-fonts/JetBrainsMono/Ligatures/JetBrainsMonoNerdFontMono-Regular.ttf
      - https://github.com/ryanoasis/nerd-fonts/raw/master/patched-fonts/JetBrainsMono/Ligatures/JetBrainsMonoNerdFontMono-Italic.ttf
      - https://github.com/ryanoasis/nerd-fonts/raw/master/patched-fonts/JetBrainsMono/Ligatures/JetBrainsMonoNerdFontMono-Bold.ttf
      - https://github.com/ryanoasis/nerd-fonts/raw/master/patched-fonts/JetBrainsMono/Ligatures/JetBrainsMonoNerdFontMono-BoldItalic.ttf
      # UbuntuMono Nerd Font
      - https://github.com/ryanoasis/nerd-fonts/raw/master/patched-fonts/UbuntuMono/UbuntuMonoNerdFontMono-Regular.ttf
      - https://github.com/ryanoasis/nerd-fonts/raw/master/patched-fonts/UbuntuMono/UbuntuMonoNerdFontMono-Italic.ttf
      - https://github.com/ryanoasis/nerd-fonts/raw/master/patched-fonts/UbuntuMono/UbuntuMonoNerdFontMono-Bold.ttf
      - https://github.com/ryanoasis/nerd-fonts/raw/master/patched-fonts/UbuntuMono/UbuntuMonoNerdFontMono-BoldItalic.ttf

  tasks:
    - ansible.builtin.set_fact: is_wsl={{ lookup('file', '/proc/version') is regex('(M|m)icrosoft') }}

    - name: "[WSL] Get Windows folder"
      ansible.builtin.shell: wslpath "$(cmd.exe /c "echo %WINDIR%" 2>/dev/null)"
      register: windir
      when: is_wsl

    - name: "[WSL] Get user's Windows home folder"
      ansible.builtin.shell: wslpath "$(cmd.exe /c "echo %USERPROFILE%" 2>/dev/null)"
      register: userprofile
      when: is_wsl

    - name: "[WSL] Link Windows fonts into WSL"
      become: yes
      ansible.builtin.copy:
        dest: /etc/fonts/local.conf
        content: |
          <?xml version="1.0"?>
          <!DOCTYPE fontconfig SYSTEM "fonts.dtd">
          <fontconfig>
              <dir>{{ windir.stdout }}/Fonts</dir>
              <dir>{{ userprofile.stdout }}/AppData/Local/Microsoft/Windows/Fonts</dir>
          </fontconfig>
      when: is_wsl

    - name: "[Non-WSL] Ensure /usr/local/share/fonts exists"
      become: yes
      ansible.builtin.file:
        path: /usr/local/share/fonts
        state: directory
      when: not is_wsl

    - name: "[Non-WSL] Install Fonts (downloaded)"
      become: yes
      ansible.builtin.get_url:
        url: "{{ item }}"
        dest: /usr/local/share/fonts/
      loop: "{{ fonts }}"
      register: fonts_downloaded
      when: not is_wsl

    - name: "[Non-WSL] Update font cache"
      become: yes
      ansible.builtin.command: fc-cache -sv
      when: not is_wsl and fonts_downloaded.changed

    - name: "[Non-WSL] Update customization with kwriteconfig5"
      ansible.builtin.command: kwriteconfig5 --file ~/.config/{{ item.file }} --group {{ item.group }} --key "{{ item.key }}" "{{ item.value }}"
      loop: "{{ kde_config }}"
      when: not is_wsl
