- name: "Core OS customization (terminal)"
  hosts: 127.0.0.1
  connection: local

  tasks:
    - name: "Remove old common bash aliases"
      ansible.builtin.blockinfile:
        path: ~/.bashrc
        marker: "### {mark} Ansible managed: Bash aliases (common)"
        state: absent

    - name: "Remove old Linux bash aliases"
      ansible.builtin.blockinfile:
        path: ~/.bashrc
        marker: "### {mark} Ansible managed: Bash aliases (Linux)"
        state: absent

    - name: "Add bash aliases"
      ansible.builtin.blockinfile:
        path: ~/.bashrc
        marker: "### {mark} Ansible managed: Bash aliases"
        block: |
          alias diff='colordiff'
          alias dir='ls -lA'
          alias ll='ls -l'

          alias ..='cd ..'
          alias ...='cd ../..'
          alias ....='cd ../../..'
          alias .....='cd ../../../..'
          alias ......='cd ../../../../..'

          alias clip='xclip -selection clipboard'
          alias grep='grep --color=auto'
          alias ls='ls -Fh --color'

          alias gpg-stop='gpgconf --kill gpg-agent'

          alias wsl='wsl.exe'

          export LS_COLORS='ow=93'

    - name: "Install package"
      become: yes
      ansible.builtin.dnf:
        name: "{{ item }}"
      loop:
        - colordiff
        - fastfetch
        - fortune-mod

    - name: "Ensure fastfetch configuration folder exists"
      ansible.builtin.file:
        path: ~/.config/fastfetch
        state: directory

    - name: "Override fastfetch configuration"
      ansible.builtin.copy:
        dest: ~/.config/fastfetch/config.jsonc
        mode: 0755
        content: |
          {
            "$schema": "https://github.com/fastfetch-cli/fastfetch/raw/master/doc/json_schema.json",
            "modules": [
              "title",
              "break",
              "os",
              "kernel",
              "uptime",
              "localip",
              "break",
              "host",
              "cpu",
              "memory",
              "gpu",
              "display",
              "disk",
              "battery"
            ]
          }

    - name: "Add fastfetch & fortune to ~/.bashrc"
      ansible.builtin.blockinfile:
        path: ~/.bashrc
        marker: "### {mark} Ansible managed: login banner"
        block: |
          echo ""
          fastfetch
          echo ""
          fortune

    - name: "Disable sudo password requirement"
      become: yes
      ansible.builtin.lineinfile:
        path: /etc/sudoers
        line: "{{ lookup('env', 'USER') }} ALL=(ALL) NOPASSWD: ALL"

    - name: "Enhance terminal prompt"
      ansible.builtin.blockinfile:
        path: ~/.bashrc
        marker: "### {mark} Ansible managed: prompt enhancement"
        block: |
          if [ -z "$WSL_DISTRO_NAME" ]; then
            # Write current path in the terminal title bar
            function writeCwdInTitlebar() {
              case "$TERM" in
                xterm*|rxvt*)
                  echo -ne "\033]0;`whoami`@`hostname`: `dirs +0`\007\c"
                  ;;
                *)
                  ;;
              esac
            }
          else
            # Write current path in the terminal title bar
            function writeCwdInTitlebar() {
              case "$TERM" in
                xterm*|rxvt*)
                  echo -ne "\033]0;`dirs +0`᲻\007\c"
                  ;;
                *)
                  ;;
              esac
            }

            # Set up support for X server in WSL if we don't have the built-in Wayland support
            if [ -z "${WAYLAND_DISPLAY}" ]; then
              export WSL_HOST_IP="$(cat /etc/resolv.conf | grep nameserver | awk '{print $2; exit;}')"
              export DISPLAY="${WSL_HOST_IP}:0.0"
            fi
          fi

          # Force newline when things don't end cleanly
          clear_newline() {
            if [ "$(__get_terminal_column)" != 0 ]; then
              echo -e '\033[7m%\033[0m'
            fi
          }

          __get_terminal_column() {
            exec < /dev/tty
            local oldstty=$(stty -g)
            stty raw -echo min 0
            echo -en "\033[6n" > /dev/tty
            local pos
            IFS=';' read -r -d R -a pos
            stty $oldstty
            echo "$((${pos[1]} - 1))"
          }

          PROMPT_COMMAND="clear_newline;writeCwdInTitlebar;"

          # Environment customization
          export ANSIBLE_NOCOWS=1
          export CLICOLOR=1
          export GREP_COLORS='1;35;40'
          export LSCOLORS=GxFxCxDxBxegedabagaced

          # Create a bunch of symlinks to known things in OneDrive
          if [ -d ~/OneDrive ]; then

            # TODO: How many of these things can/should be raw automated?

            if [ ! -e ~/.config/git/config ]; then
              mkdir -p ~/.config/git
              chmod 700 ~/.config
              ln -s $HOME/OneDrive/Development/.config/git/config ~/.config/git
            fi

            if [ ! -e ~/.git-credentials ]; then
              ln -s $HOME/OneDrive/Development/.git-credentials ~/
            fi

            if [ ! -d ~/.gnupg ]; then
              mkdir -p ~/.gnupg
              chmod 700 ~/.gnupg
            fi

            ln -fs $HOME/OneDrive/Development/.gnupg/* ~/.gnupg/

            if [ -d ~/OneDrive/Development/.ssh ]; then
              mkdir -p ~/.ssh
              chmod 700 ~/.ssh
              ln -fs $HOME/OneDrive/Development/.ssh/* ~/.ssh/
              chmod 700 ~/.ssh/* 2>/dev/null

              if [ ! -e ~/.ssh/authorized_keys ]; then
                ln -s $HOME/OneDrive/Development/.ssh/id_rsa.pub ~/.ssh/authorized_keys
              fi
            fi

            if [ -d ~/OneDrive/Development/bin ]; then
              export PATH=~/OneDrive/Development/bin:$PATH
            fi

          fi

          # Start in the ~/dev folder when it exists (and we're in an interactive shell)
          if [ -d ~/dev ]; then
            case "$-" in
              *i*) cd ~/dev ;;
              *)   ;;
            esac
          fi
