- name: Remmina
  hosts: 127.0.0.1
  connection: local

  tasks:
    - name: Add Remmina APT package repository
      become: yes
      apt_repository:
        repo: ppa:remmina-ppa-team/remmina-next
        filename: remmina
        update_cache: no
      register: apt_repository

    - name: Update APT package list
      become: yes
      apt:
        update_cache: yes
      when: apt_repository.changed
      register: apt_update
      retries: 5
      until: apt_update is success

    - name: Install Remmina
      become: yes
      apt:
        package: remmina
