- name: "Starship"
  hosts: 127.0.0.1
  connection: local

  tasks:
    - name: "Enable Starship COPR repository"
      become: yes
      ansible.builtin.shell: dnf -y copr enable atim/starship
      args:
        creates: /etc/yum.repos.d/_copr:copr.fedorainfracloud.org:atim:starship.repo

    - name: "Install package"
      become: yes
      ansible.builtin.dnf:
        name: "{{ item }}"
      loop:
        - starship

    - name: "Ensure ~/.config folder exists"
      ansible.builtin.file:
        path: ~/.config
        state: directory
        mode: 0700

    - name: "Copy starship.toml to ~/.config"
      ansible.builtin.copy:
        src: starship.toml
        dest: ~/.config/starship.toml

    - name: "Enable Starship in bash"
      ansible.builtin.blockinfile:
        path: ~/.bashrc
        marker: "### {mark} Ansible managed: Starship"
        block: |
          eval "$(starship init bash)"

    - name: "Ensure PowerShell config folder exists"
      ansible.builtin.file:
        path: ~/.config/powershell
        state: directory
        mode: 0700

    - name: "Ensure PowerShell profile exists"
      ansible.builtin.copy:
        content: ""
        dest: ~/.config/powershell/Microsoft.PowerShell_profile.ps1
        force: false
        mode: 0600

    - name: "Enable Starship in PowerShell"
      ansible.builtin.blockinfile:
        path: ~/.config/powershell/Microsoft.PowerShell_profile.ps1
        marker: "### {mark} Ansible managed: Starship"
        block: |
          function Invoke-Starship-PreCommand {
            $host.ui.Write("`e]0;$($PWD.Path.Replace($env:USERPROFILE ?? $env:HOME, '~'))`a")
          }
          Invoke-Expression (&starship init powershell)
