- name: TOML (VS Code)
  hosts: 127.0.0.1
  connection: local

  tasks:
    - name: Install VS Code extensions
      command: ../vscode/invoke-code --install-extension {{ item }}
      args:
        creates: ~/.vscode/extensions/{{ item }}-*/package.json
      loop:
        - tamasfe.even-better-toml
