# Ported from https://www.reddit.com/r/gnome/comments/2hj8bx/has_anyone_figured_out_a_way_to_keep_the_screen/cktqjqd/
# We don't use the ZIP file as-is because we want to dynamically enable it to support our verison of GNOME shell.
- name: No Screen Blank
  hosts: 127.0.0.1
  connection: local

  vars:
    distribution_fallback:
      'Pop!_OS': 'Ubuntu'
    distribution: "{{ distribution_fallback[ansible_distribution] | default(ansible_distribution) }}"
    is_ubu_22_04: "{{ distribution == 'Ubuntu' and (ansible_distribution_major_version | int) == 22 }}"
    is_ubu_24_04: "{{ distribution == 'Ubuntu' and (ansible_distribution_major_version | int) == 24 }}"

  tasks:
    - set_fact: is_wsl={{ lookup('file', '/proc/version') is regex('(M|m)icrosoft') }}

    - name: "[Non-WSL] Make temporary folder"
      file:
        path: /tmp/gnome-extensions/no-screen-blank
        state: directory
      when: not is_wsl

    - name: "[Non-WSL, Gnome 42] Copy extension code"
      copy:
        src: extension_v42.js
        dest: /tmp/gnome-extensions/no-screen-blank/extension.js
      when: not is_wsl and is_ubu_22_04
      register: extension_src

    - name: "[Non-WSL, Gnome 46] Copy extension code"
      copy:
        src: extension_v46.js
        dest: /tmp/gnome-extensions/no-screen-blank/extension.js
      when: not is_wsl and is_ubu_24_04
      register: extension_src

    - name: "[Non-WSL] Get GNOME shell version"
      shell: gnome-shell --version
      when: not is_wsl
      register: gnome_shell_raw

    - name: "[Non-WSL] Extract GNOME shell version"
      set_fact:
        gnome_shell_version: "{{ gnome_shell_raw.stdout | regex_search(regexp, '\\1') }}"
      vars:
        regexp: 'GNOME Shell ((\d+)\.(\d+))'
      when: not is_wsl

    - name: "[Non-WSL] Create extension manifest"
      blockinfile:
        path: /tmp/gnome-extensions/no-screen-blank/metadata.json
        create: yes
        marker: '{mark}'
        marker_begin: '{'
        marker_end: '}'
        block: |
          "shell-version": ["{{ gnome_shell_version[0] }}"],
          "uuid": "no-screen-blank@localhost",
          "name": "No Screen Blank",
          "description": "Disable blanking the screen after showing the lock screen"
      when: not is_wsl
      register: metadata_src

    - name: "[Non-WSL] Remove old ZIP file"
      file:
        path: /tmp/gnome-extensions/no-screen-blank@localhost.zip
        state: absent
      when: not is_wsl and (extension_src.changed or metadata_src.changed)

    - name: "[Non-WSL] Create extension ZIP"
      command: zip -j ../no-screen-blank@localhost.zip extension.js metadata.json
      args:
        chdir: /tmp/gnome-extensions/no-screen-blank
      when: not is_wsl and (extension_src.changed or metadata_src.changed)
      register: extension_zip

    - name: "[Non-WSL] Install extension"
      shell: gnome-extensions install /tmp/gnome-extensions/no-screen-blank@localhost.zip
      when: not is_wsl and extension_zip.changed
