# Ported from https://www.reddit.com/r/gnome/comments/2hj8bx/has_anyone_figured_out_a_way_to_keep_the_screen/cktqjqd/
# We don't use the ZIP file as-is because we want to dynamically enable it to support our verison of GNOME shell.
- name: No Screen Blank
  hosts: 127.0.0.1
  connection: local

  vars:
    distribution_fallback:
      'Pop!_OS': 'Ubuntu'
    distribution: "{{ distribution_fallback[ansible_distribution] | default(ansible_distribution) }}"
    is_ubu_22_04: "{{ distribution == 'Ubuntu' and (ansible_distribution_major_version | int) == 22 }}"
    is_ubu_24_04: "{{ distribution == 'Ubuntu' and (ansible_distribution_major_version | int) == 24 }}"

  tasks:
    - set_fact: is_wsl={{ lookup('file', '/proc/version') is regex('(M|m)icrosoft') }}

    - name: "[Non-WSL] Create extension directory"
      file:
        path: ~/.local/share/gnome-shell/extensions/no-screen-blank@localhost
        state: directory
      register: folder
      when: not is_wsl

    - name: "[Non-WSL, Gnome 42] Copy extension code"
      copy:
        src: extension_v42.js
        dest: ~/.local/share/gnome-shell/extensions/no-screen-blank@localhost/extension.js
      when: folder.changed and is_ubu_22_04

    - name: "[Non-WSL, Gnome 46] Copy extension code"
      copy:
        src: extension_v46.js
        dest: ~/.local/share/gnome-shell/extensions/no-screen-blank@localhost/extension.js
      when: folder.changed and is_ubu_24_04

    - name: "[Non-WSL] Get GNOME shell version"
      shell: gnome-shell --version
      when: folder.changed
      register: gnome_shell_raw

    - name: "[Non-WSL] Extraction GNOME shell version"
      set_fact:
        gnome_shell_version: "{{ gnome_shell_raw.stdout | regex_search(regexp, '\\1') }}"
      vars:
        regexp: 'GNOME Shell ((\d+)\.(\d+))'
      when: folder.changed

    - name: "[Non-WSL] Create extension manifest"
      blockinfile:
        path: ~/.local/share/gnome-shell/extensions/no-screen-blank@localhost/metadata.json
        create: yes
        marker: '{mark}'
        marker_begin: '{'
        marker_end: '}'
        block: |
          "shell-version": ["{{ gnome_shell_version[0] }}"],
          "uuid": "no-screen-blank@localhost",
          "name": "No Screen Blank",
          "description": "Disable blanking the screen after showing the lock screen"
      when: folder.changed
      register: metadata

    - name: "[Non-WSL] Enable extension"
      shell: gnome-extensions enable no-screen-blank@localhost
      ignore_errors: yes
      when: folder.changed and metadata.changed
