- name: "Broot"
  hosts: 127.0.0.1
  connection: local

  tasks:
    - name: "Enable broot COPR repository"
      become: yes
      ansible.builtin.shell: dnf -y copr enable sisyphus1813/broot
      args:
        creates: /etc/yum.repos.d/_copr:copr.fedorainfracloud.org:sisyphus1813:broot.repo

    - name: "Install package"
      become: yes
      ansible.builtin.dnf:
        name: "{{ item }}"
      loop:
        - broot
      register: broot_install

    - name: "Run post-download install"
      ansible.builtin.shell: broot --install
      when: broot_install.changed
