- name: Slack
  hosts: 127.0.0.1
  connection: local

  tasks:
    - set_fact: is_wsl={{ lookup('file', '/proc/version') is regex('(M|m)icrosoft') }}

    - name: "[Non-WSL] Add Slack APT package key"
      become: yes
      get_url:
        url: https://packagecloud.io/slacktechnologies/slack/gpgkey
        dest: /etc/apt/trusted.gpg.d/slack.asc
        mode: 0644
      when: not is_wsl

    - name: "[Non-WSL] Add Slack APT package repository"
      become: yes
      apt_repository:
        repo: deb https://packagecloud.io/slacktechnologies/slack/debian/ jessie main
        filename: slack
        update_cache: no
      register: apt_repository
      when: not is_wsl

    - name: "[Non-WSL] Update APT package list"
      become: yes
      apt:
        update_cache: yes
      when: apt_repository.changed
      register: apt_update
      retries: 5
      until: apt_update is success

    - name: "[Non-WSL] Install Slack Desktop"
      become: yes
      apt:
        package: slack-desktop
      when: not is_wsl
