- name: Zoom
  hosts: 127.0.0.1
  connection: local

  vars:
    is_mac: "{{ ansible_distribution == 'MacOSX' }}"

  tasks:
    - set_fact: is_wsl={{ not is_mac and lookup('file', '/proc/version') is regex('(M|m)icrosoft') }}

    # Linux

    - name: Install Zoom (Linux)
      become: yes
      apt:
        deb: https://zoom.us/client/latest/zoom_amd64.deb
      when: not is_mac and not is_wsl

    # macOS

    - name: Install Zoom (macOS)
      homebrew_cask:
        name: zoomus
      when: is_mac
