- name: "Docker"
  hosts: 127.0.0.1
  connection: local

  tasks:
    - name: "Install package"
      become: yes
      ansible.builtin.dnf:
        name: "{{ item }}"
      loop:
        - runc
        - moby-engine
        - docker-compose-switch

    - name: "Enable Docker engine for current user"
      become: yes
      ansible.builtin.user:
        name: "{{ lookup('env', 'USER') }}"
        groups: docker
        append: yes
