- name: Google Backup and Sync
  hosts: 127.0.0.1
  connection: local

  vars:
    distribution_fallback:
      'Pop!_OS': 'Ubuntu'
    distribution: "{{ distribution_fallback[ansible_distribution] | default(ansible_distribution) }}"
    distribution_release_fallback:
      'noble': 'bionic'
      'jammy': 'bionic'
    distribution_release: "{{ distribution_release_fallback[ansible_distribution_release] | default(ansible_distribution_release) }}"

  tasks:
    - set_fact: is_wsl={{ lookup('file', '/proc/version') is regex('(M|m)icrosoft') }}

    - name: "[WSL] Get user's Windows home path"
      shell: wslpath "$(cmd.exe /c "echo %USERPROFILE%" 2>/dev/null)"
      register: userprofile
      when: is_wsl

    - name: "[WSL] Check for Google Drive folder"
      stat:
        path: "{{ userprofile.stdout }}/Google Drive"
      register: gdrive_path
      when: is_wsl

    - name: "[WSL] Create symlink to ~/gdrive"
      file:
        path: ~/gdrive
        src: "{{ userprofile.stdout }}/Google Drive"
        state: link
      when: is_wsl and gdrive_path.stat.exists

    - name: "[Non-WSL] Add Insync APT package key"
      become: yes
      get_url:
        url: https://keyserver.ubuntu.com/pks/lookup?op=get&search=0xaeeb94e9c5a3b54ecfa4a66aa684470caccaf35c
        dest: /etc/apt/trusted.gpg.d/insync.asc
        mode: 0644
      when: not is_wsl

    - name: "[Non-WSL] Add Insync APT package repository"
      become: yes
      apt_repository:
        repo: deb http://apt.insynchq.com/{{ distribution | lower }} {{ distribution_release }} non-free contrib
        filename: insync
        update_cache: no
      register: apt_repository
      when: not is_wsl

    - name: "[Non-WSL] Update APT package list"
      become: yes
      apt:
        update_cache: yes
      when: apt_repository.changed
      register: apt_update
      retries: 5

    - name: "[Non-WSL] Install Insync"
      become: yes
      apt:
        package: "{{ item }}"
      loop:
        - insync
      when: not is_wsl
