- name: bat (customization)
  hosts: 127.0.0.1
  connection: local

  tasks:
    - name: Ensure configuration folder exists
      become: yes
      file:
        path: ~/.config/bat
        state: directory

    - name: Add configuration file
      blockinfile:
        path: ~/.config/bat/config
        create: true
        marker: "### {mark} Ansible managed: bat customization"
        # Note: You may want --theme="Visual Studio Dark+" if you plan to run a dark mode terminal
        # You can run 'bat --list-themes' and choose the one that works best for you
        block: |
          --tabs=4
          --theme="GitHub"
          --italic-text=always
          --map-syntax "*.csproj:XML"
          --map-syntax "*.ctrf:JSON"
          --map-syntax "*.fsproj:XML"
          --map-syntax "*.nuspec:XML"
          --map-syntax "*.props:XML"
          --map-syntax "*.targets:XML"
          --map-syntax "*.trx:XML"
          --map-syntax "*.vbproj:XML"

    - name: Alias bat to cat
      blockinfile:
        path: ~/.bashrc
        marker: "### {mark} Ansible managed: bat customization"
        block: |
          alias cat='bat -pp'
