- name: Zscaler Intermediate Root CA
  hosts: 127.0.0.1
  connection: local

  tasks:
    - name: "Trust the Zscaler Root CA"
      become: yes
      copy:
        src: ZscalerRootCA.pem
        dest: /usr/local/share/ca-certificates/zscaler.crt
        mode: 0644
      register: zscaler_cert

    - name: "Update CA certs"
      become: yes
      command: 
        cmd: update-ca-certificates -f
      when: zscaler_cert.changed

    - name: Set up environment for the Zscaler certificate
      blockinfile:
        path: ~/.bashrc
        marker: "### {mark} Ansible managed: Zscaler certificate"
        block: |
          export CERT_PATH=/etc/ssl/certs/ca-certificates.crt
          export CERT_DIR=/etc/ssl/certs/
          export SSL_CERT_FILE=${CERT_PATH}
          export SSL_CERT_DIR=${CERT_DIR}
          export REQUESTS_CA_BUNDLE=${CERT_PATH}
          export LC_ALL=C
