- name: "VS Code"
  hosts: 127.0.0.1
  connection: local

  tasks:
    - ansible.builtin.set_fact: is_wsl={{ lookup('file', '/proc/version') is regex('(M|m)icrosoft') }}

    - name: "[WSL] Get user's Windows home path"
      ansible.builtin.shell: wslpath "$(cmd.exe /c "echo %USERPROFILE%" 2>/dev/null)"
      register: userprofile
      when: is_wsl

    - name: "[WSL] Create shortcut to Windows ~/.vscode"
      ansible.builtin.file:
        path: ~/.vscode
        src: "{{ userprofile.stdout }}/.vscode"
        state: link
      when: is_wsl

    - name: "[WSL] Ensure ~/.config folder exists"
      ansible.builtin.file:
        path: ~/.config
        state: directory
      when: is_wsl

    - name: "[WSL] Create shortcut to Windows ~/.config/Code"
      ansible.builtin.file:
        path: ~/.config/Code
        src: "{{ userprofile.stdout }}/AppData/Roaming/Code"
        state: link
      when: is_wsl

    - name: "[Non-WSL] Import Microsoft package key"
      become: yes
      ansible.builtin.rpm_key:
        key: https://packages.microsoft.com/keys/microsoft.asc
      when: not is_wsl

    - name: "[Non-WSL] Add VS Code package repository"
      become: yes
      ansible.builtin.yum_repository:
        name: vscode-yum
        description: vscode-yum
        baseurl: https://packages.microsoft.com/yumrepos/vscode
        gpgkey: https://packages.microsoft.com/keys/microsoft.asc
      when: not is_wsl

    - name: "[Non-WSL] Install package"
      become: yes
      ansible.builtin.dnf:
        name: "{{ item }}"
      loop:
        - code
      when: not is_wsl
