- name: .NET
  hosts: 127.0.0.1
  connection: local

  vars:
    distribution_fallback:
      'Pop!_OS': 'Ubuntu'
    distribution_release_fallback:
      'impish': 'hirsute'
    distribution_version_fallback:
      '21.10': '21.04'
    dotnet_runtime_versions:
      - "3.1"
    dotnet_sdk_version: "6.0"
    is_mac: "{{ ansible_distribution == 'MacOSX' }}"

  tasks:
    # Linux

    - name: Add Microsoft APT package key
      become: yes
      apt_key:
        url: https://packages.microsoft.com/keys/microsoft.asc
      when: not is_mac

    - name: Add Microsoft APT package repository
      become: yes
      apt_repository:
        repo: deb [arch=amd64] https://packages.microsoft.com/{{ distribution_fallback[ansible_distribution] | default(ansible_distribution) | lower }}/{{ ansible_distribution_major_version if ansible_distribution == 'Debian' else distribution_version_fallback[ansible_distribution_version] | default(ansible_distribution_version) }}/prod {{ distribution_release_fallback[ansible_distribution_release] | default(ansible_distribution_release) }} main
        filename: microsoft-prod
        update_cache: no
      register: apt_repository
      when: not is_mac

    - name: Update APT package list
      become: yes
      apt:
        update_cache: yes
      when: apt_repository.changed
      register: apt_update
      retries: 5
      until: apt_update is success

    - name: Install .NET SDK {{ dotnet_sdk_version }} (Linux)
      become: yes
      apt:
        package: dotnet-sdk-{{ dotnet_sdk_version }}
      register: dotnet_sdk_installed_linux
      when: not is_mac

    - name: Install ASP.NET Runtime (Linux)
      become: yes
      apt:
        package: aspnetcore-runtime-{{ item }}
      loop: "{{ dotnet_runtime_versions }}"
      when: not is_mac

    - name: Perform first-run experience (Linux)
      command: dotnet new
      when: dotnet_sdk_installed_linux.changed

    # macOS

    - name: Install .NET SDK installer
      get_url:
        url: https://dot.net/v1/dotnet-install.sh
        dest: ~/bin/dotnet-install
        mode: 0755
      when: is_mac

    - name: Install .NET SDK {{ dotnet_sdk_version }} (macOS)
      shell: ~/bin/dotnet-install -c {{ dotnet_sdk_version }}
      register: dotnet_sdk_installed_mac
      args:
        creates: ~/.dotnet/sdk/{{ dotnet_sdk_version }}.*/.version
      when: is_mac

    - name: Install ASP.NET Runtime (macOS)
      shell: ~/bin/dotnet-install -c {{ item }} --runtime aspnetcore
      loop: "{{ dotnet_runtime_versions }}"
      args:
        creates: ~/.dotnet/shared/Microsoft.NETCore.App/{{ item }}.*/.version
      when: is_mac

    - name: Create shortcut to dotnet
      file:
        path: ~/bin/dotnet
        src: ~/.dotnet/dotnet
        state: link
      when: is_mac

    - name: Perform first-run experience (macOS)
      command: ~/bin/dotnet new
      when: dotnet_sdk_installed_mac.changed

    # Common

    - name: Update environment for .NET Core
      blockinfile:
        path: ~/.bashrc
        marker: "### {mark} Ansible managed: .NET Core enhancement"
        block: |
          export PATH=$PATH:$HOME/.dotnet/tools
