- name: .NET
  hosts: 127.0.0.1
  connection: local

  vars:
    dotnet_runtime_versions: ["6.0"]
    dotnet_sdk_version: "8.0"

  tasks:
    - name: Create ~/.dotnet
      file:
        path: ~/.dotnet
        state: directory
        mode: 0755

    - name: Download dotnet-install
      get_url:
        url: https://dot.net/v1/dotnet-install.sh
        dest: ~/bin/dotnet-install
        mode: 0755

    - name: Install .NET SDK {{ dotnet_sdk_version }}
      command: ~/bin/dotnet-install --channel {{ dotnet_sdk_version }}
      args:
        creates: ~/.dotnet/sdk/{{ dotnet_sdk_version }}.*/
      register: dotnet_sdk_installed_linux

    - name: Install ASP.NET Runtime
      command: ~/bin/dotnet-install --channel {{ item }} --runtime aspnetcore
      args:
        creates: ~/.dotnet/shared/Microsoft.AspNetCore.App/{{ item }}.*/
      loop: "{{ dotnet_runtime_versions }}"

    - name: Perform first-run experience
      command: ~/.dotnet/dotnet new
      when: dotnet_sdk_installed_linux.changed

    - name: Update environment for .NET
      blockinfile:
        path: ~/.bashrc
        marker: "### {mark} Ansible managed: .NET Core enhancement"
        block: |
          export PATH=$PATH:$HOME/.dotnet:$HOME/.dotnet/tools
