- name: .NET
  hosts: 127.0.0.1
  connection: local

  vars:
    dotnet_runtime_versions: ["latest", "8.0"]

  tasks:
    - name: Create ~/.local/share/dnvm
      file:
        path: ~/.local/share/dnvm
        state: directory
        mode: 0755

    # We download a known old version of dnvm so that we can update, which does the equivalent
    # of a non-interactive install. In particular, it will extract the `env` file, and add things
    # to the .bashrc to put `dnvm` and `dotnet` on the path
    - name: Download dnvm
      ansible.builtin.unarchive:
        src: https://github.com/dn-vm/dnvm/releases/download/v0.9.7/dnvm-0.9.7-linux-x64.tar.gz
        remote_src: yes
        dest: ~/.local/share/dnvm
        creates: ~/.local/share/dnvm/dnvm

    - name: Install dnvm
      ansible.builtin.command: ~/.local/share/dnvm/dnvm update --self
      args:
        creates: ~/.local/share/dnvm/env

    - name: Install .NET Runtime
      ansible.builtin.command: ~/.local/share/dnvm/dnvm track {{ item }}
      loop: "{{ dotnet_runtime_versions }}"

    - name: Perform first-run experience
      ansible.builtin.command: ~/.local/share/dnvm/dotnet new
