- name: .NET
  hosts: 127.0.0.1
  connection: local

  vars:
    distribution_fallback:
      'Pop!_OS': 'Ubuntu'
    distribution: "{{ distribution_fallback[ansible_distribution] | default(ansible_distribution) }}"
    dotnet_runtime_versions: ["6.0"]
    dotnet_sdk_version: "8.0"
    is_ubu_22_04_or_newer: "{{ distribution == 'Ubuntu' and (ansible_distribution_major_version | int) >= 22 }}"

  tasks:
    - name: Add Microsoft APT package key
      become: yes
      get_url:
        url: https://packages.microsoft.com/keys/microsoft.asc
        dest: /etc/apt/keyrings/microsoft-prod.asc
        mode: 0644

    - name: Add Microsoft APT package repository
      become: yes
      apt_repository:
        repo: deb [arch=amd64, signed-by=/etc/apt/keyrings/microsoft-prod.asc] https://packages.microsoft.com/{{ distribution | lower }}/{{ ansible_distribution_version }}/prod {{ ansible_distribution_release }} main
        filename: microsoft-prod
        update_cache: no
      register: apt_repository

    - name: Prefer Microsoft APT package repository
      become: yes
      copy:
        src: 10microsoft
        dest: /etc/apt/preferences.d/

    - name: Update APT package list
      become: yes
      apt:
        update_cache: yes
      when: apt_repository.changed
      register: apt_update
      retries: 5
      until: apt_update is success

    - name: Install .NET SDK {{ dotnet_sdk_version }}
      become: yes
      apt:
        package: dotnet-sdk-{{ dotnet_sdk_version }}
      register: dotnet_sdk_installed_linux

    - name: Install ASP.NET Runtime
      become: yes
      apt:
        package: aspnetcore-runtime-{{ item }}
      loop: "{{ dotnet_runtime_versions }}"

    - name: Perform first-run experience
      command: dotnet new
      when: dotnet_sdk_installed_linux.changed

    - name: Update environment for .NET
      blockinfile:
        path: ~/.bashrc
        marker: "### {mark} Ansible managed: .NET Core enhancement"
        block: |
          export PATH=$PATH:$HOME/.dotnet/tools
