- name: Beyond Compare
  hosts: 127.0.0.1
  connection: local

  tasks:
    - name: Add Scooter Software APT package key
      become: yes
      get_url:
        url: https://www.scootersoftware.com/DEB-GPG-KEY-scootersoftware.asc
        dest: /etc/apt/trusted.gpg.d/DEB-GPG-KEY-scootersoftware.asc
        mode: 0644

    - name: Add Beyond Compare APT package repository
      become: yes
      apt_repository:
        repo: deb [arch=amd64] https://www.scootersoftware.com/debian/ bcompare5 non-free
        filename: scootersoftware
        update_cache: no
      register: apt_repository

    - name: Update APT package list
      become: yes
      apt:
        update_cache: yes
      when: apt_repository.changed
      register: apt_update
      retries: 5
      until: apt_update is success

    - name: Install Beyond Compare
      become: yes
      apt:
        package: bcompare

    - name: Add bcomp alias
      file:
        path: ~/bin/bcomp
        src: /usr/bin/bcompare
        state: link
