- name: Beyond Compare
  hosts: 127.0.0.1
  connection: local

  vars:
    is_mac: "{{ ansible_distribution == 'MacOSX' }}"

  tasks:
    # Linux

    - name: Add Scooter Software APT package key
      become: yes
      apt_key:
        url: https://www.scootersoftware.com/RPM-GPG-KEY-scootersoftware
      when: not is_mac

    - name: Add Beyond Compare APT package repository
      become: yes
      apt_repository:
        repo: deb http://www.scootersoftware.com/ bcompare4 non-free
        filename: scootersoftware
        update_cache: no
      register: apt_repository
      when: not is_mac

    - name: Update APT package list
      become: yes
      apt:
        update_cache: yes
      when: apt_repository.changed
      register: apt_update
      retries: 5
      until: apt_update is success

    - name: Install Beyond Compare (Linux)
      become: yes
      apt:
        package: bcompare
      when: not is_mac

    # macOS

    - name: Install Beyond Compare (macOS)
      homebrew_cask:
        name: beyond-compare
      when: is_mac
