- name: Google Chrome
  hosts: 127.0.0.1
  connection: local

  tasks:
    - set_fact: is_wsl={{ lookup('file', '/proc/version') is regex('(M|m)icrosoft') }}

    - name: Add Google APT package key
      become: yes
      apt_key:
        url: https://dl.google.com/linux/linux_signing_key.pub
      when: not is_wsl

    - name: Add Google Chrome APT package repository
      become: yes
      apt_repository:
        repo: deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main
        filename: google-chrome
        update_cache: no
      register: apt_repository
      when: not is_wsl

    - name: Update APT package list
      become: yes
      apt:
        update_cache: yes
      when: not is_wsl and apt_repository.changed
      register: apt_update
      retries: 5
      until: apt_update is success

    - name: Install Google Chrome
      become: yes
      apt:
        package: google-chrome-stable
      when: not is_wsl
