- name: Fulcrum
  hosts: 127.0.0.1
  connection: local

  tasks:
    - name: Install Fulcrum packages via homebrew
      homebrew:
        name: "{{ item }}"
      loop:
      - gawk
      - graphviz
      - helm
      - istioctl
      - kubectl
      - pre-commit
      - shellcheck
      - terraform-docs
      - tfenv
      - tflint
      - tfsec
      - warrensbox/tap/tgswitch

      # This one requires gcc. Skipping for now,
      # we don't use eks anyhow
      # - weaveworks/tap/eksctl
