- name: Fulcrum
  hosts: 127.0.0.1
  connection: local

  tasks:
    # requires: `ansible-galaxy collection install community.general`

    # - name: Tap the required Homebrew repositories
    #   community.general.homebrew_tap:
    #     name: weaveworks/tap,sigsegv13/tgenv
    #
    # That wasn't working for me so I did this manually: 
    # - brew tap weaveworks/tap
    # - brew tap sigsegv13/tgenv

    - name: Install Fulcrum packages via homebrew
      homebrew:
        name: "{{ item }}"
      loop:
      - gawk
      - graphviz
      - helm
      - istioctl
      - kubectl
      - pre-commit
      - shellcheck
      - terraform-docs
      - tfenv
      - tflint
      - tfsec
      - warrensbox/tap/tgswitch

      # This one requires gcc. Skipping for now,
      # we don't use eks anyhow
      # - weaveworks/tap/eksctl
