- name: NodeJS
  hosts: 127.0.0.1
  connection: local

  tasks:
    - name: Install Node Version Manager
      shell:
        cmd: "curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.39.7/install.sh | bash"
        warn: false
      args:
        creates: ~/.nvm/install.sh
