- name: Microsoft Edge
  hosts: 127.0.0.1
  connection: local

  tasks:
    - set_fact: is_wsl={{ lookup('file', '/proc/version') is regex('(M|m)icrosoft') }}

    # Linux

    - name: "[Non-WSL] Add Microsoft APT package repository"
      become: yes
      apt_repository:
        repo: deb [arch=amd64] https://packages.microsoft.com/repos/edge/ stable main
        filename: microsoft-edge
        update_cache: no
      register: apt_repository
      when: not is_wsl

    - name: "[Non-WSL] Update APT package list"
      become: yes
      apt:
        update_cache: yes
      when: apt_repository.changed
      register: apt_update
      retries: 5
      until: apt_update is success

    - name: "[Non-WSL] Install Microsoft Edge"
      become: yes
      apt:
        package: "{{ item }}"
      loop:
        - fonts-liberation
        - microsoft-edge-stable
      when: not is_wsl
