- name: "Remmina"
  hosts: 127.0.0.1
  connection: local

  tasks:
    - ansible.builtin.set_fact: is_wsl={{ lookup('file', '/proc/version') is regex('(M|m)icrosoft') }}

    - name: "[Non-WSL] Install package"
      become: yes
      ansible.builtin.dnf:
        name: "{{ item }}"
      loop:
        - remmina
      when: not is_wsl
