- name: "Rust"
  hosts: 127.0.0.1
  connection: local

  tasks:
    - name: "Install package"
      become: yes
      ansible.builtin.dnf:
        name: "{{ item }}"
      loop:
        - rust
        - cargo

    - name: "Add cargo binaries to the path"
      ansible.builtin.blockinfile:
        path: ~/.bashrc
        marker: "### {mark} Ansible managed: Rust configuration"
        block: |
          export PATH=$PATH:~/.cargo/bin
