- name: Rust
  hosts: 127.0.0.1
  connection: local

  tasks:
    - name: Install pre-requisites
      become: yes
      apt:
        package: "{{ item }}"
      loop:
        - build-essential
        - curl
        - gcc
        - make

    - name: Install Rust
      shell:
        cmd: curl https://sh.rustup.rs -sSf | sh -s -- -y
        warn: false
        creates: ~/.cargo/bin/cargo
