- name: Mono
  hosts: 127.0.0.1
  connection: local

  vars:
    distribution_fallback:
      'Pop!_OS': 'Ubuntu'
    distribution: "{{ distribution_fallback[ansible_distribution] | default(ansible_distribution) }}"
    distribution_release_fallback:
      'jammy': 'focal'
    distribution_release: "{{ distribution_release_fallback[ansible_distribution_release] | default(ansible_distribution_release) }}"

  tasks:
    - set_fact: is_wsl={{ lookup('file', '/proc/version') is regex('(M|m)icrosoft') }}

    - name: Add Mono APT package key
      become: yes
      get_url:
        url: https://keyserver.ubuntu.com/pks/lookup?op=get&search=0x3fa7e0328081bff6a14da29aa6a19b38d3d831ef
        dest: /etc/apt/keyrings/mono-official-stable.asc
        mode: 0644

    - name: Add Mono APT package repository
      become: yes
      apt_repository:
        repo: deb [arch=amd64, signed-by=/etc/apt/keyrings/mono-official-stable.asc] https://download.mono-project.com/repo/{{ distribution | lower }} stable-{{ distribution_release }} main
        filename: mono-official-stable
        update_cache: no
      register: apt_repository

    - name: Update APT package list
      become: yes
      apt:
        update_cache: yes
      when: apt_repository.changed
      register: apt_update
      retries: 5
      until: apt_update is success

    - name: Install Mono
      become: yes
      apt:
        package: "{{ item }}"
      loop:
        - mono-complete
        - mono-vbnc
      register: mono_install

    - name: "[WSL] Disable .NET app auto-run with Mono (now)"
      become: yes
      shell: update-binfmts --disable cli
      when: is_wsl

    - name: "[WSL] Disable .NET app auto-run with Mono (on startup)"
      blockinfile:
        path: ~/.bashrc
        marker: "### {mark} Ansible managed: Disable Mono auto-run for Windows apps (WSL)"
        block: |
          sudo update-binfmts --disable cli
      when: is_wsl
