- name: Mono (VS Code)
  hosts: 127.0.0.1
  connection: local

  tasks:
    - name: Install VS Code extensions
      command: ../vscode/invoke-code --install-extension {{ item }}
      args:
        creates: ~/.vscode/extensions/{{ item }}-*/package.json
      loop:
        - k--kato.docomment        # C# XML Documentation Comments
        - ms-dotnettools.csharp    # C#
        - ms-vscode.mono-debug     # Mono Debug
